### ISSUE TITLE
Backwards compatibility issue with aespriteSheet support

### ISSUE THREAD

**Issue by charlestudor** [replit/kaboom#21]
The issue is that earlier versions of aesprite export invalid spritesheet JSON that Kaboom does not recognise.

At the very least v1.1.6 exports unrecognised JSON. (The difference in this version is simply that "frames" is an object rather than an array of objects. An easy manual fix) 

I'm not sure which aesprite version changed the export format (or how many variations there are)

This might be an issue for the documentation rather than the library itself, as you may not wish the hassle of supporting every different export format that was in use.

Many Thanks!

**Comment by slmjkdbtl** [comment]
You have to export json with "Array" instead of "Hash" (default in Aseprite), cuz iterating the JSON object doesn't ensure the order with "Hash". I'll make it clear in the docs.

<img width="611" alt="1618593132" src="https://user-images.githubusercontent.com/9929523/115060058-64a90600-9eb5-11eb-987f-c1fb6de3e638.png">

**Comment by charlestudor** [comment]
Silly me! Thanks for the quick response, I'll close this issue.

**Comment by slmjkdbtl** [comment]
No worry!
