### ISSUE TITLE
Feature suggestion: display hit boxes when in debug mode

### ISSUE THREAD

**Issue by oaklandgit** [replit/kaboom#67]
When debugging collisions, it's helpful to see the hit boxes. Suggest showing them when in debug mode.

**Comment by slmjkdbtl** [comment]
debug mode basically enables pressing f1 to toggle hit boxes (see [here](https://github.com/replit/kaboom/blob/b55f2168a05494fe48f94b1d1eff9a2f41155172/src/kaboom.ts#L391-L427)), kept it to a key binding instead of all the time because rendering hitboxes for all objects is actually not cheap. But you can always manually set `debug.inspect = true` on start

**Comment by oaklandgit** [comment]
Thank you @slmjkdbtl ! That makes sense and I can't believe I missed that this is already implemented!

**Comment by triptych** [comment]
The challenge is more of a documentation / example issue now :)

**Comment by slmjkdbtl** [comment]
Yep. Right now it's written in the `kaboom()` function section in the docs, I'll reiterate them on the debug section as well.
