### ISSUE TITLE
Safari: SyntaxError: Unexpected token '{'

### ISSUE THREAD

**Issue by peratik** [replit/kaboom#769]
Hi

Safari 14.1.2
macOS Catalina
kaboom 3000.1.12
using cdn: https://unpkg.com/kaboom@3000.1.12/dist/kaboom.js

`<script src='https://unpkg.com/kaboom@3000.1.12/dist/kaboom.js' />` shows `SyntaxError: Unexpected token '{'` in the console.

Pease advice.

**Comment by slmjkdbtl** [comment]
Weird, I cannot reproduce it. Do you have a full HTML code for me to paste and try?

**Comment by peratik** [comment]
https://salmon-lesya-53.tiiny.site/

![image](https://github.com/replit/kaboom/assets/6568353/9f707005-faf2-4d81-8190-4731bde1f218)

**Comment by ilovecoding69420** [comment]
> https://salmon-lesya-53.tiiny.site/

You need to load the kaboom(); after you load the lib. Tested on safari mobile.
https://jsfiddle.net/1yxrz4c2/

**Comment by slmjkdbtl** [comment]
Your code has another error: the `<script>` containing `kaboom()` needs to be put inside `<body>` instead of `<head>`, because `kaboom()` requires `document.body`. After fixing that, it runs well on my Safari mobile (iOS 16.6.1).

However I'm still unable to reproduce the syntax error you mentioned, which version of iOS are you on?

**Comment by peratik** [comment]
Updated: https://azure-harriott-9.tiiny.site/

It is not Safari mobile, It is on Desktop

Safari 14.1.2
macOS Catalina

![image](https://github.com/replit/kaboom/assets/6568353/7ce1d1e5-928e-4729-a614-55e1acb27357)
