### ISSUE TITLE
text component shows text pixlated

### ISSUE THREAD

**Issue by peratik** [replit/kaboom#776]
![image](https://github.com/replit/kaboom/assets/6568353/1ddb57e4-f851-4ba9-aec2-2308cf87a761)

```
loadFont('roboto-bold', './Roboto-Bold.ttf');
text(value.toString(), {
   align: 'center',
   size: 18,
   font: 'roboto-bold',
   width: 36,
})
```

Hi, It is not sharp and pixelated, How can fix it?

**Comment by slmjkdbtl** [comment]
Can you try

```js
loadFont('roboto-bold', './Roboto-Bold.ttf', { filter: "linear" });
```

to see if it's better?

**Comment by peratik** [comment]
![image](https://github.com/replit/kaboom/assets/6568353/1d0f52da-f611-4410-bb3b-d2b2ce71135c)

With `linear` filter it is still pixelated.

**Comment by p2edwards** [comment]
- Are you wanting the text to be sharper than the canvas it's rendering into? 
- Are you wanting something subtle, like better font hinting, maybe subpixel font rendering?

I might be wrong but I think your options are to

1. (if you're stretching the canvas to fit the screen) — Increase canvas resolution (might impact performance and affect your other graphics)
2. (advanced) Try to render text in the browser "in front of" the canvas element. I don't think there's a built-in easy way to do this with Kaboom, but I'm mentioning it because it's technically doable and will look as good as any other text in the browser.

**Comment by peratik** [comment]
How can we increase canvas resolution?

**Comment by slmjkdbtl** [comment]
You can try increasing `pixelDensity`
```js
kaboom({
    pixelDensity: 2,
})
```
You can get your current `pixelDensity` by `window.devicePixelRatio`, and try some higher value (higher value will cost performance)

**Comment by slmjkdbtl** [comment]
For all non-bitmap fonts kaboom uses canvas 2d context to render to a texture, using a [fixed font size of 64](https://github.com/replit/kaboom/blob/088419750f2931744bb74e0df677ba4689ba72f8/src/kaboom.ts#L205), it might be a good idea to make it customizable so you can render the font to a larger size so it works better for scaling like
```js
loadFont('roboto-bold', './Roboto-Bold.ttf', { size: 120 });
```

**Comment by peratik** [comment]
`pixelDensity` solutions works. thank you.

`size: 120` is not available in the current Kaboom release, it would be great to have it.
